root_path = "D:/多模态任务/MMW2NER/"
# root_path = "/root/autodl-tmp/MMW2NER/"
pinyin_vocab_path = "data/pingyin_vocab.npy"
radical_vocab_path = "data/chaizi-jt.txt"
# bert_path = "model/bert-base-chinese"
# bert_path = "model/roberta-wwm-large"
bert_path = "model/bert-wwm-chinese"
bert_path = 'model/guwenbert-large'
ttf_paths = ['data/ttf/simhei.ttf', 'data/ttf/fangsong.ttf', 'data/ttf/kaiti.ttf']